workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TITLE != $DOCS_AUTOCOMMIT_TITLE
    - if: $CI_COMMIT_BRANCH =~ /^manticore-.*$/ && $CI_COMMIT_TITLE != $DOCS_AUTOCOMMIT_TITLE
    - if: $TEST || $WHAT

# to skip ci add [ci skip] or [skip ci] in commit message in any capitalization

stages:
  - mirroring

job_mirror:
  stage: mirroring
  rules:
    - if: $TEST==null && $CI_COMMIT_BRANCH == "master"
  tags:
    - dev-host
  dependencies: []
  script:
    - ~/gitsync_columnar.sh
  cache: {}

